# test_trace_exception